version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5050:5050"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
